### ISSUE TITLE
only part of the database is accessible 

### ISSUE THREAD

**Issue by mz0in** [sqlchat/sqlchat#84]
### Describe the bug

1- prompt : 
would you give me all tables in the database
....... 
result : 
it return only 6 tables out of 63 
---
2- prompt : 
would you check there is a 63 table in the database
...

I'm sorry, but I cannot check if there are 63 tables in the database as the provided database schema only includes the SQL code for creating six tables. If there are additional tables in the database, I would need access to the database to view them.

### To reproduce

would you give me all tables in the database

**Comment by emostar** [comment]
I'm seeing only 4 out of 84 tables.

**Comment by tianzhou** [comment]
This is due to the token limitation. In new version, you can now select the table you want

![CleanShot 2023-06-07 at 23-45-40 png](https://github.com/sqlchat/sqlchat/assets/230323/87c3e043-8612-43ea-a413-2b379fe2862f)

and view the actual token prompt used

![CleanShot 2023-06-07 at 23-46-50 png](https://github.com/sqlchat/sqlchat/assets/230323/f4c5e4fd-8c81-4293-b4f5-b5b94de7e5d7)


![CleanShot 2023-06-07 at 23-46-22 png](https://github.com/sqlchat/sqlchat/assets/230323/b7872689-8267-4654-9f30-0980af674203)
